/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'inkball.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _GUID;
struct _s_ThrowInfo;
struct _s_CatchableTypeArray;
struct _s_CatchableType;
struct _devicemodeW;
struct HDC__;
struct HWND__;
struct HMENU__;
struct tagWNDCLASSEXW;
struct HINSTANCE__;
struct HICON__;
struct HBRUSH__;
union _LARGE_INTEGER;
struct HACCEL__;
struct _EXCEPTION_RECORD;
struct _CONTEXT;
struct HKEY__;
struct _SECURITY_ATTRIBUTES;
struct HRSRC__;
struct HBITMAP__;

/* 1 */
typedef struct _GUID GUID;

/* 2 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 3 */
enum __bitmask __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 4 */
enum __bitmask __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 5 */
struct FuncInfo
{
  unsigned __int32 magicNumber : 29;
  unsigned __int32 bbtFlags : 3;
  int maxState __dec;
  void *pUnwindMap;
  int nTryBlocks __dec;
  void *pTryBlockMap;
  int nIPMapEntries __dec;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags __hex;
};

/* 6 */
struct UnwindMapEntry
{
  int toState __dec;
  void *action;
};

/* 7 */
struct TryBlockMapEntry
{
  int tryLow __dec;
  int tryHigh __dec;
  int catchHigh __dec;
  int nCatches __dec;
  void *pHandlerArray;
};

/* 8 */
struct HandlerType
{
  int adjectives __hex;
  void *pType;
  int dispCatchObj __dec;
  void *addressOfHandler;
};

/* 9 */
struct TypeDescriptor
{
  void *pVFTable;
  void *spare;
  char name[] __strlit(C,"windows-1252");
};

/* 10 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 12 */
typedef unsigned int DWORD;

/* 11 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 13 */
typedef void *PVOID;

/* 14 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 15 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 16 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 17 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 18 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 20 */
typedef unsigned __int64 ULONG64;

/* 19 */
typedef ULONG64 TRACEHANDLE;

/* 21 */
typedef const GUID *LPCGUID;

/* 22 */
typedef unsigned __int16 USHORT;

/* 24 */
typedef const struct _s_ThrowInfo ThrowInfo;

/* 23 */
typedef ThrowInfo _ThrowInfo;

/* 26 */
typedef void (__cdecl *PMFN)(void *);

/* 27 */
typedef const struct _s_CatchableTypeArray CatchableTypeArray;

/* 25 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int (__cdecl *pForwardCompat)();
  CatchableTypeArray *pCatchableTypeArray;
};
#pragma pack(pop)

/* 29 */
typedef const struct _s_CatchableType CatchableType;

/* 28 */
#pragma pack(push, 4)
struct _s_CatchableTypeArray
{
  int nCatchableTypes;
  CatchableType *arrayOfCatchableTypes[];
};
#pragma pack(pop)

/* 31 */
#pragma pack(push, 4)
struct PMD
{
  int mdisp;
  int pdisp;
  int vdisp;
};
#pragma pack(pop)

/* 30 */
#pragma pack(push, 4)
struct _s_CatchableType
{
  unsigned int properties;
  TypeDescriptor *pType;
  PMD thisDisplacement;
  int sizeOrOffset;
  PMFN copyFunction;
};
#pragma pack(pop)

/* 33 */
typedef unsigned __int16 wchar_t;

/* 32 */
typedef wchar_t WCHAR;

/* 34 */
typedef void *LPVOID;

/* 35 */
typedef struct _devicemodeW DEVMODEW;

/* 37 */
typedef unsigned __int16 WORD;

/* 39 */
struct _devicemodeW::$5A39A2C3BB0B1D2D5888DFEE2BA0B23C::$A4EE175A7532F35C00DA5CAD042934DF
{
  __int16 dmOrientation;
  __int16 dmPaperSize;
  __int16 dmPaperLength;
  __int16 dmPaperWidth;
  __int16 dmScale;
  __int16 dmCopies;
  __int16 dmDefaultSource;
  __int16 dmPrintQuality;
};

/* 43 */
typedef int LONG;

/* 42 */
struct _POINTL
{
  LONG x;
  LONG y;
};

/* 41 */
typedef struct _POINTL POINTL;

/* 40 */
struct _devicemodeW::$5A39A2C3BB0B1D2D5888DFEE2BA0B23C::$604F2BC6924E02F5722A52FC79BC44F9
{
  POINTL dmPosition;
  DWORD dmDisplayOrientation;
  DWORD dmDisplayFixedOutput;
};

/* 38 */
union _devicemodeW::$5A39A2C3BB0B1D2D5888DFEE2BA0B23C
{
  struct
  {
    __int16 dmOrientation;
    __int16 dmPaperSize;
    __int16 dmPaperLength;
    __int16 dmPaperWidth;
    __int16 dmScale;
    __int16 dmCopies;
    __int16 dmDefaultSource;
    __int16 dmPrintQuality;
  };
  struct
  {
    POINTL dmPosition;
    DWORD dmDisplayOrientation;
    DWORD dmDisplayFixedOutput;
  };
};

/* 44 */
union _devicemodeW::$4FBEBCCE69364E072421C9DF045BB77C
{
  DWORD dmDisplayFlags;
  DWORD dmNup;
};

/* 36 */
struct _devicemodeW
{
  WCHAR dmDeviceName[32];
  WORD dmSpecVersion;
  WORD dmDriverVersion;
  WORD dmSize;
  WORD dmDriverExtra;
  DWORD dmFields;
  union
  {
    struct
    {
      __int16 dmOrientation;
      __int16 dmPaperSize;
      __int16 dmPaperLength;
      __int16 dmPaperWidth;
      __int16 dmScale;
      __int16 dmCopies;
      __int16 dmDefaultSource;
      __int16 dmPrintQuality;
    };
    struct
    {
      POINTL dmPosition;
      DWORD dmDisplayOrientation;
      DWORD dmDisplayFixedOutput;
    };
  };
  __int16 dmColor;
  __int16 dmDuplex;
  __int16 dmYResolution;
  __int16 dmTTOption;
  __int16 dmCollate;
  WCHAR dmFormName[32];
  WORD dmLogPixels;
  DWORD dmBitsPerPel;
  DWORD dmPelsWidth;
  DWORD dmPelsHeight;
  union
  {
    DWORD dmDisplayFlags;
    DWORD dmNup;
  };
  DWORD dmDisplayFrequency;
  DWORD dmICMMethod;
  DWORD dmICMIntent;
  DWORD dmMediaType;
  DWORD dmDitherType;
  DWORD dmReserved1;
  DWORD dmReserved2;
  DWORD dmPanningWidth;
  DWORD dmPanningHeight;
};

/* 45 */
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};

/* 46 */
typedef struct tagRECT RECT;

/* 47 */
typedef const WCHAR *LPCWSTR;

/* 48 */
typedef struct HDC__ *HDC;

/* 49 */
struct HDC__
{
  int unused;
};

/* 50 */
typedef DWORD COLORREF;

/* 51 */
typedef struct HWND__ *HWND;

/* 52 */
struct HWND__
{
  int unused;
};

/* 54 */
enum $590B73EBA2289426BF23338FF0AEEAF9
{
  WMI_GET_ALL_DATA = 0x0,
  WMI_GET_SINGLE_INSTANCE = 0x1,
  WMI_SET_SINGLE_INSTANCE = 0x2,
  WMI_SET_SINGLE_ITEM = 0x3,
  WMI_ENABLE_EVENTS = 0x4,
  WMI_DISABLE_EVENTS = 0x5,
  WMI_ENABLE_COLLECTION = 0x6,
  WMI_DISABLE_COLLECTION = 0x7,
  WMI_REGINFO = 0x8,
  WMI_EXECUTE_METHOD = 0x9,
  WMI_CAPTURE_STATE = 0xA,
};

/* 53 */
typedef enum $590B73EBA2289426BF23338FF0AEEAF9 WMIDPREQUESTCODE;

/* 56 */
typedef void *HANDLE;

/* 55 */
struct _TRACE_GUID_REGISTRATION
{
  LPCGUID Guid;
  HANDLE RegHandle;
};

/* 57 */
typedef wchar_t *STRSAFE_LPWSTR;

/* 58 */
typedef unsigned int size_t;

/* 60 */
typedef int BOOL;

/* 61 */
typedef unsigned __int8 BYTE;

/* 59 */
struct tagPAINTSTRUCT
{
  HDC hdc;
  BOOL fErase;
  RECT rcPaint;
  BOOL fRestore;
  BOOL fIncUpdate;
  BYTE rgbReserved[32];
};

/* 62 */
typedef struct HMENU__ *HMENU;

/* 63 */
struct HMENU__
{
  int unused;
};

/* 64 */
struct _OSVERSIONINFOW
{
  DWORD dwOSVersionInfoSize;
  DWORD dwMajorVersion;
  DWORD dwMinorVersion;
  DWORD dwBuildNumber;
  DWORD dwPlatformId;
  WCHAR szCSDVersion[128];
};

/* 65 */
typedef unsigned int UINT;

/* 67 */
typedef unsigned int UINT_PTR;

/* 66 */
typedef UINT_PTR WPARAM;

/* 69 */
typedef int LONG_PTR;

/* 68 */
typedef LONG_PTR LPARAM;

/* 70 */
typedef struct tagWNDCLASSEXW WNDCLASSEXW;

/* 73 */
typedef LONG_PTR LRESULT;

/* 72 */
typedef LRESULT (__stdcall *WNDPROC)(HWND, UINT, WPARAM, LPARAM);

/* 74 */
typedef struct HINSTANCE__ *HINSTANCE;

/* 76 */
typedef struct HICON__ *HICON;

/* 78 */
typedef HICON HCURSOR;

/* 79 */
typedef struct HBRUSH__ *HBRUSH;

/* 71 */
struct tagWNDCLASSEXW
{
  UINT cbSize;
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCWSTR lpszMenuName;
  LPCWSTR lpszClassName;
  HICON hIconSm;
};

/* 75 */
struct HINSTANCE__
{
  int unused;
};

/* 77 */
struct HICON__
{
  int unused;
};

/* 80 */
struct HBRUSH__
{
  int unused;
};

/* 81 */
typedef WCHAR *LPWSTR;

/* 82 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 84 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 85 */
typedef __int64 LONGLONG;

/* 83 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 86 */
typedef struct HACCEL__ *HACCEL;

/* 87 */
struct HACCEL__
{
  int unused;
};

/* 90 */
struct tagPOINT
{
  LONG x;
  LONG y;
};

/* 89 */
typedef struct tagPOINT POINT;

/* 88 */
struct tagMSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};

/* 91 */
typedef unsigned int ULONG;

/* 93 */
typedef BYTE *LPBYTE;

/* 92 */
struct _STARTUPINFOW
{
  DWORD cb;
  LPWSTR lpReserved;
  LPWSTR lpDesktop;
  LPWSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 94 */
typedef int (__cdecl *_onexit_t)();

/* 95 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 97 */
typedef struct _EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 101 */
typedef struct _CONTEXT CONTEXT;

/* 100 */
typedef CONTEXT *PCONTEXT;

/* 96 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 99 */
typedef unsigned int ULONG_PTR;

/* 98 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  struct _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 104 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Cr0NpxState;
};

/* 103 */
typedef struct _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 102 */
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};

/* 105 */
typedef void *HGDIOBJ;

/* 106 */
typedef struct tagRECT *LPRECT;

/* 107 */
typedef struct HKEY__ *HKEY;

/* 108 */
struct HKEY__
{
  int unused;
};

/* 110 */
typedef DWORD ACCESS_MASK;

/* 109 */
typedef ACCESS_MASK REGSAM;

/* 111 */
typedef HKEY *PHKEY;

/* 112 */
typedef struct _SECURITY_ATTRIBUTES *LPSECURITY_ATTRIBUTES;

/* 113 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 114 */
typedef DWORD *LPDWORD;

/* 115 */
typedef HINSTANCE HMODULE;

/* 116 */
typedef struct HRSRC__ *HRSRC;

/* 117 */
struct HRSRC__
{
  int unused;
};

/* 118 */
typedef const WCHAR *PCWSTR;

/* 119 */
struct CGameObject;

/* 120 */
struct std::bad_alloc;

/* 121 */
struct CGameBoard;

/* 122 */
struct CGameManager;

/* 123 */
struct CSink;

/* 124 */
struct exception;

/* 125 */
struct Helpers::CLogBlock;

/* 126 */
struct Helpers;

/* 127 */
struct TabUtils;

/* 128 */
struct CBall;

/* 129 */
struct BallPoints;

/* 130 */
struct CBoardObject;

/* 131 */
struct CMovingObject;

/* 132 */
struct CSurface;

/* 133 */
struct CBallManager;

/* 134 */
struct CBoardManager;

/* 135 */
struct CBoardTile;

/* 136 */
struct CBoardTileChevron;

/* 137 */
struct CBoardTileRLColored;

/* 138 */
struct CInk;

/* 139 */
struct CScoreManager;

/* 140 */
struct CDisplay;

/* 141 */
struct CBitmapRects;

/* 142 */
struct CUIBarObject;

/* 143 */
struct CTimeManager;

/* 145 */
typedef float FLOAT;

/* 144 */
struct tagXFORM
{
  FLOAT eM11;
  FLOAT eM12;
  FLOAT eM21;
  FLOAT eM22;
  FLOAT eDx;
  FLOAT eDy;
};

/* 146 */
struct CRegistryManager;

/* 147 */
struct CTileManager;

/* 149 */
union _DDSURFACEDESC2::$091DBF7D405BE25E65B16620C008128B
{
  LONG lPitch;
  DWORD dwLinearSize;
};

/* 150 */
union _DDSURFACEDESC2::$E56E877DD0D4D3B03846BC7047D947ED
{
  DWORD dwBackBufferCount;
  DWORD dwDepth;
};

/* 151 */
union _DDSURFACEDESC2::$F25F5019EA70F6B9B11866A0D418A260
{
  DWORD dwMipMapCount;
  DWORD dwRefreshRate;
  DWORD dwSrcVBHandle;
};

/* 154 */
struct _DDCOLORKEY
{
  DWORD dwColorSpaceLowValue;
  DWORD dwColorSpaceHighValue;
};

/* 153 */
typedef struct _DDCOLORKEY DDCOLORKEY;

/* 152 */
union _DDSURFACEDESC2::$5B12F1D1A21F9ED7C15CB39448B5A42D
{
  DDCOLORKEY ddckCKDestOverlay;
  DWORD dwEmptyFaceColor;
};

/* 158 */
union _DDPIXELFORMAT::$F1D3FB4D78950D0942225445130999CB
{
  DWORD dwRGBBitCount;
  DWORD dwYUVBitCount;
  DWORD dwZBufferBitDepth;
  DWORD dwAlphaBitDepth;
  DWORD dwLuminanceBitCount;
  DWORD dwBumpBitCount;
  DWORD dwPrivateFormatBitCount;
};

/* 159 */
union _DDPIXELFORMAT::$6A86D2BA2D533C5D3D5AB1F1491969D5
{
  DWORD dwRBitMask;
  DWORD dwYBitMask;
  DWORD dwStencilBitDepth;
  DWORD dwLuminanceBitMask;
  DWORD dwBumpDuBitMask;
  DWORD dwOperations;
};

/* 161 */
struct _DDPIXELFORMAT::$4689F3D0B997E93FAF3E67A693E85360::$A78036EB239B85FA27F661E6E98FFEA9
{
  WORD wFlipMSTypes;
  WORD wBltMSTypes;
};

/* 160 */
union _DDPIXELFORMAT::$4689F3D0B997E93FAF3E67A693E85360
{
  DWORD dwGBitMask;
  DWORD dwUBitMask;
  DWORD dwZBitMask;
  DWORD dwBumpDvBitMask;
  struct _DDPIXELFORMAT::$4689F3D0B997E93FAF3E67A693E85360::$A78036EB239B85FA27F661E6E98FFEA9 MultiSampleCaps;
};

/* 162 */
union _DDPIXELFORMAT::$4C86B66084EB9B6F3AE81991D3FADB38
{
  DWORD dwBBitMask;
  DWORD dwVBitMask;
  DWORD dwStencilBitMask;
  DWORD dwBumpLuminanceBitMask;
};

/* 163 */
union _DDPIXELFORMAT::$23DF69239FC04D9BE22118E1AD8451FB
{
  DWORD dwRGBAlphaBitMask;
  DWORD dwYUVAlphaBitMask;
  DWORD dwLuminanceAlphaBitMask;
  DWORD dwRGBZBitMask;
  DWORD dwYUVZBitMask;
};

/* 157 */
struct _DDPIXELFORMAT
{
  DWORD dwSize;
  DWORD dwFlags;
  DWORD dwFourCC;
  union
  {
    DWORD dwRGBBitCount;
    DWORD dwYUVBitCount;
    DWORD dwZBufferBitDepth;
    DWORD dwAlphaBitDepth;
    DWORD dwLuminanceBitCount;
    DWORD dwBumpBitCount;
    DWORD dwPrivateFormatBitCount;
  };
  union
  {
    DWORD dwRBitMask;
    DWORD dwYBitMask;
    DWORD dwStencilBitDepth;
    DWORD dwLuminanceBitMask;
    DWORD dwBumpDuBitMask;
    DWORD dwOperations;
  };
  union
  {
    DWORD dwGBitMask;
    DWORD dwUBitMask;
    DWORD dwZBitMask;
    DWORD dwBumpDvBitMask;
    struct _DDPIXELFORMAT::$4689F3D0B997E93FAF3E67A693E85360::$A78036EB239B85FA27F661E6E98FFEA9 MultiSampleCaps;
  };
  union
  {
    DWORD dwBBitMask;
    DWORD dwVBitMask;
    DWORD dwStencilBitMask;
    DWORD dwBumpLuminanceBitMask;
  };
  union
  {
    DWORD dwRGBAlphaBitMask;
    DWORD dwYUVAlphaBitMask;
    DWORD dwLuminanceAlphaBitMask;
    DWORD dwRGBZBitMask;
    DWORD dwYUVZBitMask;
  };
};

/* 156 */
typedef struct _DDPIXELFORMAT DDPIXELFORMAT;

/* 155 */
union _DDSURFACEDESC2::$640C42AFF919FFD3058B9E962436B842
{
  DDPIXELFORMAT ddpfPixelFormat;
  DWORD dwFVF;
};

/* 166 */
union _DDSCAPS2::$19AC68468C4510B3DC631A4E89752068
{
  DWORD dwCaps4;
  DWORD dwVolumeDepth;
};

/* 165 */
struct _DDSCAPS2
{
  DWORD dwCaps;
  DWORD dwCaps2;
  DWORD dwCaps3;
  union
  {
    DWORD dwCaps4;
    DWORD dwVolumeDepth;
  };
};

/* 164 */
typedef struct _DDSCAPS2 DDSCAPS2;

/* 148 */
struct _DDSURFACEDESC2
{
  DWORD dwSize;
  DWORD dwFlags;
  DWORD dwHeight;
  DWORD dwWidth;
  union
  {
    LONG lPitch;
    DWORD dwLinearSize;
  };
  union
  {
    DWORD dwBackBufferCount;
    DWORD dwDepth;
  };
  union
  {
    DWORD dwMipMapCount;
    DWORD dwRefreshRate;
    DWORD dwSrcVBHandle;
  };
  DWORD dwAlphaBitDepth;
  DWORD dwReserved;
  LPVOID lpSurface;
  union
  {
    DDCOLORKEY ddckCKDestOverlay;
    DWORD dwEmptyFaceColor;
  };
  DDCOLORKEY ddckCKDestBlt;
  DDCOLORKEY ddckCKSrcOverlay;
  DDCOLORKEY ddckCKSrcBlt;
  union
  {
    DDPIXELFORMAT ddpfPixelFormat;
    DWORD dwFVF;
  };
  DDSCAPS2 ddsCaps;
  DWORD dwTextureStage;
};

/* 167 */
typedef struct HBITMAP__ *HBITMAP;

/* 168 */
struct HBITMAP__
{
  int unused;
};

/* 170 */
typedef unsigned __int8 UCHAR;

/* 171 */
typedef unsigned __int64 ULONGLONG;

/* 169 */
struct _EVENT_DESCRIPTOR
{
  USHORT Id;
  UCHAR Version;
  UCHAR Channel;
  UCHAR Level;
  UCHAR Opcode;
  USHORT Task;
  ULONGLONG Keyword;
};

/* 172 */
struct type_info;

/* 173 */
struct CBoardTileBreakWall;

/* 174 */
struct CBoardTileBumper;

/* 175 */
struct CBoardTileOWF;

/* 176 */
struct CBoardTileRLGray;

/* 177 */
struct CBoardTileWall;

/* 178 */
struct tagSYSTEM_EVENT_DATA
{
  BYTE bModifier;
  WCHAR wKey;
  LONG xPos;
  LONG yPos;
  BYTE bCursorMode;
  DWORD dwButtonState;
};

/* 179 */
struct CBoardTileDrain;

